"""Configuration: defaults, file loading, coercion, accounts and the Config schema.

A package rather than one 969-line module. Imported as ``from src.core.config import X``
exactly as before -- the split is behind this facade, so no caller changed.
"""

from __future__ import annotations

from .defaults import (
    ACCOUNTS_FILE,
    ALGORITHMS_FILE,
    ALGORITHM_BOT_FILE,
    ALGORITHM_EQUITY_CAP,
    ALGORITHM_IDS,
    ALPACA_BASE_URL,
    ALPACA_DATA_FEED,
    ALPHA_VANTAGE_MAX_SYMBOLS,
    ALPHA_VANTAGE_NEWS_CSV,
    ALPHA_VANTAGE_NEWS_LIMIT,
    ALPHA_VANTAGE_NEWS_LOOKBACK_DAYS,
    ALPHA_VANTAGE_REQUEST_DELAY_SECONDS,
    BACKTEST_PERIOD,
    BACKTEST_STARTING_EQUITY,
    CASH_BUFFER,
    CASH_EQUIVALENTS,
    CONFIG_FILE,
    CONNECTORS_FILE,
    DCA_BOT_FILE,
    DEFAULT_STRATEGY_ID,
    DIVIDEND_PROVIDER_ORDER,
    EOD_MARKET_DATA_CACHE_TTL_SECONDS,
    EOD_MARKET_DATA_PROVIDER_ORDER,
    HISTORY_EXTRA_BUFFER_DAYS,
    INTRADAY_MARKET_DATA_CACHE_TTL_SECONDS,
    INTRADAY_MARKET_DATA_PROVIDER_ORDER,
    KILL_SWITCH,
    MARKET_DATA_BAR_MINUTES,
    MARKET_DATA_CACHE_TTL_SECONDS,
    MARKET_DATA_PROVIDER_ORDER,
    MAX_PORTFOLIO_EXPOSURE,
    MAX_WEIGHT_PER_SYMBOL,
    MIN_TRADE_DOLLARS,
    MOMENTUM_LOOKBACK_DAYS,
    NEWS_SENTIMENT_CACHE_TTL_SECONDS,
    NEWS_SENTIMENT_PROVIDER_ORDER,
    REBALANCE_THRESHOLD,
    SYMBOLS,
    TRADABLES_CSV,
    TRANSACTION_COST_BPS,
    UNIVERSE_FILE,
    UNNAMED_ACCOUNT_ID,
)
from .paths import (
    LEGACY_CONFIG_FILES,
    accounts_file_path,
    algorithm_bot_file_path,
    algorithms_file_path,
    config_file_path,
    connectors_file_path,
    universe_file_path,
)
from .yaml_io import (
    migrate_legacy_config,
    load_accounts_config,
    load_algorithm_bot_config,
    load_algorithms_config,
    load_connectors_config,
    load_universe_config,
    config_transaction,
    save_accounts_config,
    save_algorithm_bot_config,
    save_algorithms_config,
    save_universe_config,
    save_universe_symbols,
)
from .accounts import (
    UnknownAccountError,
    get_account_broker_type,
)
from .schema import (
    Config,
    get_config,
)


__all__ = [
    "ACCOUNTS_FILE",
    "ALGORITHMS_FILE",
    "ALGORITHM_BOT_FILE",
    "ALGORITHM_EQUITY_CAP",
    "ALGORITHM_IDS",
    "ALPACA_BASE_URL",
    "ALPACA_DATA_FEED",
    "ALPHA_VANTAGE_MAX_SYMBOLS",
    "ALPHA_VANTAGE_NEWS_CSV",
    "ALPHA_VANTAGE_NEWS_LIMIT",
    "ALPHA_VANTAGE_NEWS_LOOKBACK_DAYS",
    "ALPHA_VANTAGE_REQUEST_DELAY_SECONDS",
    "BACKTEST_PERIOD",
    "BACKTEST_STARTING_EQUITY",
    "CASH_BUFFER",
    "CASH_EQUIVALENTS",
    "CONFIG_FILE",
    "CONNECTORS_FILE",
    "Config",
    "DCA_BOT_FILE",
    "DEFAULT_STRATEGY_ID",
    "DIVIDEND_PROVIDER_ORDER",
    "EOD_MARKET_DATA_CACHE_TTL_SECONDS",
    "EOD_MARKET_DATA_PROVIDER_ORDER",
    "HISTORY_EXTRA_BUFFER_DAYS",
    "INTRADAY_MARKET_DATA_CACHE_TTL_SECONDS",
    "INTRADAY_MARKET_DATA_PROVIDER_ORDER",
    "KILL_SWITCH",
    "LEGACY_CONFIG_FILES",
    "MARKET_DATA_BAR_MINUTES",
    "MARKET_DATA_CACHE_TTL_SECONDS",
    "MARKET_DATA_PROVIDER_ORDER",
    "MAX_PORTFOLIO_EXPOSURE",
    "MAX_WEIGHT_PER_SYMBOL",
    "MIN_TRADE_DOLLARS",
    "MOMENTUM_LOOKBACK_DAYS",
    "NEWS_SENTIMENT_CACHE_TTL_SECONDS",
    "NEWS_SENTIMENT_PROVIDER_ORDER",
    "REBALANCE_THRESHOLD",
    "SYMBOLS",
    "TRADABLES_CSV",
    "TRANSACTION_COST_BPS",
    "UNIVERSE_FILE",
    "UNNAMED_ACCOUNT_ID",
    "UnknownAccountError",
    "accounts_file_path",
    "algorithm_bot_file_path",
    "algorithms_file_path",
    "config_file_path",
    "connectors_file_path",
    "get_account_broker_type",
    "get_config",
    "load_accounts_config",
    "load_algorithm_bot_config",
    "load_algorithms_config",
    "load_connectors_config",
    "load_universe_config",
    "migrate_legacy_config",
    "config_transaction",
    "save_accounts_config",
    "save_algorithm_bot_config",
    "save_algorithms_config",
    "save_universe_config",
    "save_universe_symbols",
    "universe_file_path",
]
